AWSTemplateFormatVersion: 2010-09-09
Description: Simple VPC basic template, with nothing other than just VPC (Worked)

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} TemplateCreatedVPC