AWSTemplateFormatVersion: 2010-09-09
Description: Learning about parameters and how to use them
Parameters:
  InstanceType:
    Description: Webserver EC2 instance type (has default, allowed values)
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.nano
      - t2.micro
      - t2.small
    ConstraintDescription: Must be valid EC2 insatnce type.

Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-a4c7edb2"
      #we reference the InstanceType Paramater here
      InstanceType: !Ref InstanceType