# Author : Akash Sisodiya
service: api-get-current-time
provider:
  name: aws
  runtime: nodejs10.x
functions:
  serverTime:
    handler: handler.serverTime
    events:
      - http:
          path: time
          method: get